##
# This playbook backs up the /etc/passwd and /etc/shadow files
##

---

  - name: Backup-passwd-File
    ansible.builtin.copy:
      remote_src: true
      src: /etc/passwd
      dest: /etc/passwd_lock.bak
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Backup-shadow-File
    ansible.builtin.copy:
      remote_src: true
      src: /etc/shadow
      dest: /etc/shadow_lock.bak
      owner: root
      group: root
      mode: u=rw,g=r

  - name: Find all directories in /home
    ansible.builtin.command: "ls /home/"
    register: home_dirs

  - name: debug-output
    debug:
      var: home_dirs.stdout_lines

  - name: lock-users
    ansible.builtin.user:
      name: "{{ item }}"
      password_lock: true
    loop: "{{ home_dirs.stdout_lines }}"
    when: item not in lock_users_whitelist
