- hosts: all # CHANGE THIS
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 192.168.1.26 # CHANGE THIS
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5

    wazuh_agent_sources_installation:
        enabled: false
        user_install_type: "agent"
        user_dir: "/var/ossec"
        user_delete_dir: "y"
        user_enable_active_response: "y"
        user_enable_syscheck: "y"
        user_enable_rootcheck: "y"
        user_enable_sca: "y"
        user_enable_authd: "y"
        user_generate_authd_cert: "n"
        user_update: "y"

    wazuh_agent_rootcheck:
      frequency: 3600 # seconds (1 hour)

    wazuh_agent_syscollector:
      disable: 'no'
      interval: '10m' # 10 minutes between each scan
      scan_on_start: 'yes'
      hardware: 'yes'
      os: 'yes'
      network: 'yes'
      packages: 'yes'
      ports_no: 'yes' # this was yes before? check this!
      processes: 'yes'

    wazuh_agent_sca:
      enabled: 'yes'
      scan_on_start: 'yes'
      interval: '1h'
      skip_nfs: 'yes'
      day: ''
      wday: ''
      time: ''

    wazuh_agent_syscheck:
      frequency: 43200
      scan_on_start: 'yes'
      auto_ignore: 'no'
      win_audit_interval: 60
      skip_nfs: 'yes'
      skip_dev: 'yes'
      skip_proc: 'yes'
      skip_sys: 'yes'
      process_priority: 10
      max_eps: 50
      sync_enabled: 'yes'
      sync_interval: '5m'
      sync_max_interval: '1h'
      sync_max_eps: 10
      ignore:
        - /etc/mtab
        - /etc/hosts.deny
        - /etc/mail/statistics
        - /etc/random-seed
        - /etc/random.seed
        - /etc/adjtime
        - /etc/httpd/logs
        - /etc/utmpx
        - /etc/wtmpx
        - /etc/cups/certs
        - /etc/dumpdates
        - /etc/svc/volatile
        - /root/.bash_history # I added this manualy boz (gnerates too much noise)
      ignore_linux_type:
        - '.log$|.swp$'
      ignore_win:
        - '.log$|.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$'
      no_diff:
        - /etc/ssl/private.key
      directories:
        # The additional directories to monitor in real time:
        - dirs: "/etc/update-motd.d/"
          checks: 'realtime="yes"'
        - dirs: "/etc/motd"
          checks: 'realtime="yes"'
        - dirs: "/etc/sudoers"
          checks: 'realtime="yes"'
        - dirs: "/etc/ssh/sshd_config"
          checks: 'realtime="yes"'
        - dirs: "/etc/sudoers.d"
          checks: 'realtime="yes"'
        - dirs: "/etc/bash/bashrc"
          checks: 'realtime="yes"'
        - dirs: "/var/ossec/etc/ossec.conf"
          checks: 'realtime="yes"'
        - dirs: "/var/spool/cron/"
          checks: 'realtime="yes"'
        - dirs: "/etc/security/"
          checks: 'realtime="yes"'
        - dirs: "/etc/hosts.allow"
          checks: 'realtime="yes"'
        - dirs: "/home/*/.ssh/authorized_keys"
          checks: 'realtime="yes"'
        - dirs: "/home/*/.bashrc"
          checks: 'realtime="yes"'
        - dirs: "/usr/bin/"
          checks: 'realtime="yes"'
        - dirs: "/usr/local/bin/"
          checks: 'realtime="yes"'
        - dirs: "/tmp/"
          checks: 'realtime="yes"'
      win_directories:
        - dirs: '%WINDIR%'
          checks: 'recursion_level="0" restrict="regedit.exe$|system.ini$|win.ini$"'
        - dirs: '%WINDIR%\SysNative'
          checks: >-
            recursion_level="0" restrict="at.exe$|attrib.exe$|cacls.exe$|cmd.exe$|eventcreate.exe$|ftp.exe$|lsass.exe$|
            net.exe$|net1.exe$|netsh.exe$|reg.exe$|regedt32.exe|regsvr32.exe|runas.exe|sc.exe|schtasks.exe|sethc.exe|subst.exe$"
        - dirs: '%WINDIR%\SysNative\drivers\etc%'
          checks: 'recursion_level="0"'
        - dirs: '%WINDIR%\SysNative\wbem'
          checks: 'recursion_level="0" restrict="WMIC.exe$"'
        - dirs: '%WINDIR%\SysNative\WindowsPowerShell\v1.0'
          checks: 'recursion_level="0" restrict="powershell.exe$"'
        - dirs: '%WINDIR%\SysNative'
          checks: 'recursion_level="0" restrict="winrm.vbs$"'
        - dirs: '%WINDIR%\System32'
          checks: >-
            recursion_level="0" restrict="at.exe$|attrib.exe$|cacls.exe$|cmd.exe$|eventcreate.exe$|ftp.exe$|lsass.exe$|net.exe$|net1.exe$|
            netsh.exe$|reg.exe$|regedit.exe$|regedt32.exe$|regsvr32.exe$|runas.exe$|sc.exe$|schtasks.exe$|sethc.exe$|subst.exe$"
        - dirs: '%WINDIR%\System32\drivers\etc'
          checks: 'recursion_level="0"'
        - dirs: '%WINDIR%\System32\wbem'
          checks: 'recursion_level="0" restrict="WMIC.exe$"'
        - dirs: '%WINDIR%\System32\WindowsPowerShell\v1.0'
          checks: 'recursion_level="0" restrict="powershell.exe$"'
        - dirs: '%WINDIR%\System32'
          checks: 'recursion_level="0" restrict="winrm.vbs$"'
        - dirs: '%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Startup'
          checks: 'realtime="yes"'
      windows_registry:
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\batfile'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\cmdfile'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\comfile'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\exefile'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\piffile'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\AllFilesystemObjects'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\Directory'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\Folder'
        - key: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Policies'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Security'
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services'
        - key: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\KnownDLLs'
        - key: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\winreg'
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx'
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
          arch: "both"
        - key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components'
          arch: "both"
        - key: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Security'
          arch: "both"
        - key: 'HKLM\SOFTWARE\Microsoft\Windows Defender'
          arch: "both"
        - key: 'HKLM\SOFTWARE\Microsoft\Windows Defender\Exclusions'
          arch: "both"
      windows_registry_ignore:
        - key: 'HKEY_LOCAL_MACHINE\Security\Policy\Secrets'
        - key: 'HKEY_LOCAL_MACHINE\Security\SAM\Domains\Account\Users'
        - key: '\Enum$'
          type: "sregex"


    wazuh_agent_localfiles:
      debian:
        - format: 'syslog'
          location: '/var/log/auth.log'
        - format: 'syslog'
          location: '/var/log/syslog'
        - format: 'syslog'
          location: '/var/log/dpkg.log'
        - format: 'syslog'
          location: '/var/log/kern.log'
      centos:
        - format: 'syslog'
          location: '/var/log/messages'
        - format: 'syslog'
          location: '/var/log/secure'
        - format: 'syslog'
          location: '/var/log/maillog'
      linux:
        - format: 'syslog'
          location: '/var/ossec/logs/active-responses.log'
        - format: 'full_command'
          command: 'last -n 20'
          frequency: '360'
        - format: 'command'
          command: df -P
          frequency: '360'
        - format: 'full_command'
          command: netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
          alias: 'netstat listening ports'
          frequency: '360'
        - format: 'audit'
          location: '/var/log/audit/audit.log' ## I added this audit log line here
      windows:
        - format: 'eventlog'
          location: 'Application'
        - format: 'eventchannel'
          location: 'Security'
          query: 'Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907]'
        - format: 'eventlog'
          location: 'System'
        - format: 'syslog'
          location: 'active-response\active-responses.log'