---
- name: Check elevation level
  ansible.builtin.win_shell: whoami /groups | findstr "High"

- name: Install IPBan via one-liner
  ansible.windows.win_powershell:
    script: |
      $ProgressPreference = 'SilentlyContinue'; 
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
      iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/DigitalRuby/IPBan/master/IPBanCore/Windows/Scripts/install_latest.ps1'))

- name: Verify IPBan exists
  win_stat:
    path: C:\Program Files\IPBan
  register: ipban_program

- debug:
    var: ipban_program.stat.exists
    
- name: Ensure IPBan service is set to auto and started
  ansible.windows.win_service:
    name: IPBanService
    start_mode: auto
    state: started

# - name: Debug IPBan command
#   win_shell: |
#     $command = "Invoke-WebRequest -Uri 'https://github.com/DigitalRuby/IPBan/releases/latest/download/IPBan-Windows.zip' -OutFile 'C:\Temp\IPBan.zip'"
#     Write-Output $command
